// Save/load (Strategy B). A save stores only the small, non-regenerable state:
// the galaxy metadata, player/cycle/weather keys, and one per-planet delta per
// visited world. The heavy terrain grids and pristine naturals are never stored —
// they regenerate deterministically from planet.id on restore (see PlanetGen /
// PlanetDelta and LoadAndSave.md §4). snapshot()/restore() are pure (no I/O); the
// save/load/export helpers wrap them around a storage backend.
const Save = (() => {
  const MAGIC            = 'SPACEEXPLORE_SAVE';
  const VERSION          = 1;
  const WORLDGEN_VERSION = 1;   // bump when worldgen output changes so old saves are refused
  const SLOT_PREFIX      = 'spaceexplore.save.';
  const DEFAULT_SLOT     = 'auto';

  // Keys that are aliases (same object reference as data nested in `galaxy` or in a
  // planetMap:* key). They aren't stored — restore re-links them by id (LoadAndSave §3.2).
  const ALIAS_KEYS = new Set(['currentSolarSystem', 'currentPlanet', 'planetMap']);

  // ---- snapshot -----------------------------------------------------------

  function snapshot() {
    if (!Datastore.has('galaxy')) return null;
    const galaxy = Datastore.get('galaxy');

    const entries = [];
    const planets = [];
    for (const key of Datastore.keys()) {
      if (ALIAS_KEYS.has(key))          continue;   // re-linked on restore
      if (key.startsWith('planetMap:')) continue;   // grids regenerate from seed
      if (key.startsWith('objects:')) {
        const id = key.slice('objects:'.length);
        const located = _locatePlanet(galaxy, id);
        if (!located) continue;
        planets.push({
          id,
          delta: PlanetDelta.capture(located.planet, located.luminosity,
                                      Datastore.get(key), located.planet.deposits || []),
        });
        continue;
      }
      const value = key === 'galaxy' ? _galaxyForSave(Datastore.get(key)) : Datastore.get(key);
      entries.push({ key, type: Datastore.getType(key), value });
    }

    return {
      magic:           MAGIC,
      version:         VERSION,
      worldgenVersion: WORLDGEN_VERSION,
      savedAt:         new Date().toISOString(),
      location:        _currentLocation(),
      entries,
      planets,
    };
  }

  // Galaxy is stored verbatim except for the two planet fields that regenerate on
  // build (deposits are delta-restored; craterMeta is re-attached by MapGen.generate),
  // so we strip them to keep the save small and single-sourced. Deep-cloned so the
  // live galaxy is untouched.
  function _galaxyForSave(galaxy) {
    const clone = JSON.parse(JSON.stringify(galaxy));
    for (const system of clone.systems || []) {
      for (const planet of system.planets || []) {
        delete planet.deposits;
        delete planet.craterMeta;
      }
    }
    return clone;
  }

  function _currentLocation() {
    const location = {};
    if (Datastore.has('currentSolarSystem')) location.systemId = Datastore.get('currentSolarSystem').id;
    if (Datastore.has('currentPlanet'))      location.planetId = Datastore.get('currentPlanet').id;
    return location;
  }

  // ---- restore ------------------------------------------------------------

  function restore(save) {
    _validate(save);                 // validate before touching the live store (LoadAndSave §3.7)

    Datastore.clear();
    PlanetGrids.reset();

    // Galaxy first — every alias and delta re-links into it.
    const entries = save.entries || [];
    const galaxyEntry = entries.find(e => e.key === 'galaxy');
    if (galaxyEntry) Datastore.init('galaxy', galaxyEntry.value, galaxyEntry.type);
    for (const e of entries) {
      if (e.key !== 'galaxy') Datastore.init(e.key, e.value, e.type);
    }

    const galaxy = Datastore.has('galaxy') ? Datastore.get('galaxy') : null;

    // Rebuild each visited planet's objects/deposits from its delta. Grids stay
    // lazy (regenerated by PlanetGrids on return); only the current one is made
    // resident below.
    for (const { id, delta } of save.planets || []) {
      const located = galaxy && _locatePlanet(galaxy, id);
      if (!located) continue;
      const applied = PlanetDelta.apply(located.planet, located.luminosity, delta);
      Datastore.init(`objects:${id}`, applied.objects, DatastoreTypes.OBJECT);
      located.planet.deposits = applied.deposits;
    }

    _relinkAliases(galaxy, save.location || {});
  }

  // currentSolarSystem/currentPlanet become the same object references found inside
  // the restored galaxy; planetMap becomes the current planet's resident grid,
  // regenerated (byte-identical) via PlanetGrids so it also joins the LRU.
  function _relinkAliases(galaxy, location) {
    if (!galaxy || !location.systemId) return;
    const system = galaxy.systems.find(s => s.id === location.systemId);
    if (!system) return;
    Datastore.init('currentSolarSystem', system, DatastoreTypes.SOLAR_SYSTEM);

    const planet = location.planetId && system.planets.find(p => p.id === location.planetId);
    if (!planet) return;
    Datastore.init('currentPlanet', planet, DatastoreTypes.PLANET);
    const map = PlanetGrids.ensureResident(planet, system.star.luminosity);
    Datastore.init('planetMap', map, DatastoreTypes.GAME_MAP);
  }

  function _validate(save) {
    if (!save || save.magic !== MAGIC) throw new Error('Save: not a SpaceExplore save file');
    if (save.version !== VERSION) {
      throw new Error(`Save: unsupported save version ${save.version} (expected ${VERSION})`);
    }
    if (save.worldgenVersion !== WORLDGEN_VERSION) {
      throw new Error(`Save: worldgen version mismatch (${save.worldgenVersion} vs ${WORLDGEN_VERSION}); a regenerated world would differ`);
    }
  }

  function _locatePlanet(galaxy, planetId) {
    for (const system of galaxy.systems || []) {
      const planet = system.planets.find(p => p.id === planetId);
      if (planet) return { planet, luminosity: system.star.luminosity };
    }
    return null;
  }

  // ---- storage backend (localStorage) + file I/O --------------------------

  // Feature-detected: returns null when localStorage is unavailable (some locked-down
  // file:// setups), so callers fall back to the file export/import path (§3.8).
  function _localStorage() {
    try {
      const ls = window.localStorage;
      const probe = '__spaceexplore_probe__';
      ls.setItem(probe, '1');
      ls.removeItem(probe);
      return ls;
    } catch (_) {
      return null;
    }
  }

  function save(slot = DEFAULT_SLOT) {
    const ls = _localStorage();
    if (!ls) return false;
    const snap = snapshot();
    if (!snap) return false;
    try {
      ls.setItem(SLOT_PREFIX + slot, JSON.stringify(snap));
      return true;
    } catch (err) {
      console.error('Save: write failed', err);
      return false;
    }
  }

  function load(slot = DEFAULT_SLOT) {
    const ls = _localStorage();
    if (!ls) return false;
    const text = ls.getItem(SLOT_PREFIX + slot);
    if (text == null) return false;
    restore(JSON.parse(text));
    return true;
  }

  function list() {
    const ls = _localStorage();
    if (!ls) return [];
    const out = [];
    for (let i = 0; i < ls.length; i++) {
      const key = ls.key(i);
      if (!key || !key.startsWith(SLOT_PREFIX)) continue;
      let savedAt = null;
      try { savedAt = JSON.parse(ls.getItem(key)).savedAt || null; } catch (_) {}
      out.push({ slot: key.slice(SLOT_PREFIX.length), savedAt });
    }
    return out.sort((a, b) => (b.savedAt || '').localeCompare(a.savedAt || ''));
  }

  function hasAnySave() {
    return list().length > 0;
  }

  function latestSlot() {
    const saves = list();
    return saves.length ? saves[0].slot : null;
  }

  function deleteSlot(slot = DEFAULT_SLOT) {
    const ls = _localStorage();
    if (ls) ls.removeItem(SLOT_PREFIX + slot);
  }

  // Portability path: download the save as a file the player can re-import elsewhere.
  function exportToFile(filename) {
    const snap = snapshot();
    if (!snap) return false;
    const blob = new Blob([JSON.stringify(snap)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename || `spaceexplore-${(snap.savedAt || '').replace(/[:.]/g, '-')}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    return true;
  }

  function importFromFile(text) {
    restore(JSON.parse(text));
    return true;
  }

  return {
    snapshot, restore,
    save, load, list, hasAnySave, latestSlot, deleteSlot,
    exportToFile, importFromFile,
  };
})();
